# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required 
#cache: packages
warnings_are_errors: false
bioc_required: true


os: 
  - linux

#dist: xenial #not working because only trusty is supported

dist: trusty 

addons:
  apt:
    packages:
      - libnetcdf-dev

r:
  - "3.3.0"

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdf-dev ; fi
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdff-dev ; fi


r-packages:
  - bio3d
  - ggplot2
  - WGCNA
  - parallel
  - data.table
  - Rcpp
  - distrEx
  - gplots
  - grDevices
  - graphics
  - outliers
  - pcaPP
  - prospectr
  - splus2R
  - stats

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)

after_success:
  -  Rscript -e 'library(covr);codecov()'


