language: r
cache: packages
warnings_are_errors: false

os: 
  - linux
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

r-packages:
  - bio3d
  - ggplot2


after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)

after_success:
  -  Rscript -e 'library(covr);codecov()'


