language: r
sudo: true
#cache: packages
warnings_are_errors: false

os: 
  - linux

addons:
  apt:
    packages:
      - libnetcdff-dev

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - sudo apt-get install libnetcdff-dev


r-packages:
  - bio3d
  - ggplot2
  - WGCNA
  - parallel
  - data.table
  - Rcpp
  - distrEx
  - gplots
  - grDevices
  - graphics
  - outliers
  - pcaPP
  - prospectr
  - splus2R
  - stats

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)

after_success:
  -  Rscript -e 'library(covr);codecov()'


